### PR TITLE
Fix the parser to generate java code from edifact schemas. Codes were…

### PR DESCRIPTION
**Pull request by mcmpp**
… not correctly added to the data elements

This is a fix for the bug that was reported [here](https://github.com/smooks/smooks-edi-cartridge/issues/125), on the second comment _"You've uncovered a bug in the schema generation code. We'll address it in RC1."_

### CODE REVIEW

**Comment by claudemamo** [comment]
Thank you for your contribution! The PR unfortunately broke a number of tests. Can you take a look?

**Comment by mcmpp** [comment]
Hi @claudemamo, I have made another change to take into consideration the test that was failing. I still have tests failing but I am pretty sure the change I made is not having an impact on them. I cannot even run the master branch tests succesfully. I might need some help on this. 

```
java.lang.RuntimeException: 
Schema Definition Error: Error loading schema due to org.xml.sax.SAXParseException; systemId: file:/home/mikel/Documents/smooks-edi-cartridge/edg/target/generated-test-resources/d03b/EDIFACT-Segments.dfdl.xsd; lineNumber: 4536; columnNumber: 47; enumeration-valid-restriction: Enumeration value '1001' is not in the value space of the base type, alpha0-3.
Schema context: file:/home/mikel/Documents/smooks-edi-cartridge/edg/target/generated-test-resources/d03b/EDIFACT-Messages.dfdl.xsd Location in file:/home/mikel/Documents/smooks-edi-cartridge/edg/target/generated-test-resources/d03b/EDIFACT-Messages.dfdl.xsd
	at org.smooks.edi.edg.EdifactDfdlSchemaGenerator.lambda$main$0(EdifactDfdlSchemaGenerator.java:100)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at org.smooks.edi.edg.EdifactDfdlSchemaGenerator.main(EdifactDfdlSchemaGenerator.java:91)
	at org.smooks.edi.edg.EdifactDfdlSchemaGeneratorTestCase.testMain(EdifactDfdlSchemaGeneratorTestCase.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExte...
```

**Comment by mcmpp** [comment]
Hi there, 

Can i have some feedback on this issue??

**Comment by claudemamo** [comment]
>I still have tests failing but I am pretty sure the change I made is not having an impact on them. I cannot even run the master branch tests succesfully. 

I successfully built the master branch on my local machine. The branch also [successfully](https://github.com/smooks/smooks-edi-cartridge/actions/runs/1753771585) passes CI. You might need to rebase your fork.

**Comment by sankethpb** [comment]
@mcmpp requesting your support on this issue.
Thank you

**Comment by sankethpb** [comment]
@claudemamo kindly suggest any temporary workaround for this. Thanks a lot for your support.

**Comment by sankethpb** [comment]
@claudemamo kindly request your support here. Thank you in advance.

**Comment by mcmpp** [comment]
Hi @claudemamo , 

now it makes more sense. I get a legit test failure. I will find the issue and try to solve it.  I will close this pull request and open a new one when solved.

**Pull request closed without merging**
